### PR TITLE
Edits for link to new docs

### PR DESCRIPTION
**Pull request by awintersi**
This page now links to ER documentation at 
https://docs.support.siren.io/siren-er/2.0.0/siren-er/siren-er-beta.html

Can we make the new URL of the ER docs as above? (currently https://docs.support.siren.io/siren-er/1.1.1/siren-er/siren-er-beta.html)

PR for the updated documentation for Siren ER which would be 2.0.0:
 https://github.com/sirensolutions/er-api/pull/36

### CODE REVIEW

**Comment by colmose** [comment]
@awintersi Once we merge the sister PR (with the update of the version in the antora.yml file to 2.0.0), the link will automatically change to 2.0.0, so that should be fine. 

(I think we should change the .adoc filename in er-api from `siren-er-beta.adoc` to `siren-er.adoc` and then the link would be https://docs.support.siren.io/siren-er/1.1.1/siren-er/siren-er.html, it looks a bit tidier and more in line with the header/content once you get into the file)

I'm going to have a quick look and see if we can use a more generic link that would link to the "latest" version of the siren-er docs in antora. I _think_ we can.

**Review by colmose — CHANGES_REQUESTED** [review]
Reassign me for review if/when you make the link changes

**Comment by awintersi** [comment]
@colmose , I have  changed the link and renamed siren-er-beta.adoc in er-api

**Review by colmose — APPROVED** [review]
Looks good, we should merge these changes once the ER docs are rebuilt and pushed live as the link won't make sense until then

**Pull request closed without merging**
